### ISSUE TITLE
Problem in meshio version

### ISSUE THREAD

**Issue by sunscale** [NEFM-TUDresden/gmshModel#3]
Hi,

Recently I installed gmshModel on a new laptop, and when I ran my old codes, there was an error:
`meshio._helpers' has no attribute 'extension_to_filetype`

After I changed 'extension_to_filetype' to 'extension_to_filetypes', it moved on but another error occurred:
`IndexError: index 60 is out of bounds for axis 0 with size 57`

I find that meshio has been upgraded a lot since last time I used gmshModel, it works well for **meshio<=5.1.2**. Some functions used in gmshModel have been deprecated in later version of meshio. I think It might be better to add this version requirement in `setup.py`.

Best,
Yulin

**Comment by PhilippMetsch** [comment]
Hi, 
sorry for the late reply. I did not have the time to check out the issues arising from the recent developments of dependent packages. I fixed the issue by restricting the meshio version to <=5.1.2, temporarily. At least on PyPi, the new version of gmshModel is available and should be working without these issues
